# Generated by Django 5.0.6 on 2025-12-10 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='payment_slips/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verify_status', models.CharField(choices=[('unverified', 'ยังไม่ตรวจสอบ'), ('passed', 'ผ่านการตรวจสอบ'), ('mismatch', 'ข้อมูลไม่ตรงกัน'), ('error', 'เกิดข้อผิดพลาด')], default='unverified', max_length=15)),
                ('verify_message', models.TextField(blank=True)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ocr_account', models.CharField(blank=True, max_length=50)),
                ('ocr_datetime', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_slip', to='orders.order')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
