# Generated by Django 5.0.6 on 2025-12-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSlip',
        ),
    ]
