# Generated by Django 5.0.6 on 2026-03-13 07:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_delete_paymentslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('kbank', 'ธนาคารกสิกรไทย'), ('scb', 'ธนาคารไทยพาณิชย์'), ('bbl', 'ธนาคารกรุงเทพ'), ('ktb', 'ธนาคารกรุงไทย'), ('ttb', 'ธนาคารทหารไทยธนชาต (TTB)'), ('gsb', 'ธนาคารออมสิน'), ('bay', 'ธนาคารกรุงศรีอยุธยา'), ('promptpay', 'พร้อมเพย์'), ('other', 'อื่นๆ')], max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('completed', 'โอนแล้ว'), ('rejected', 'ปฏิเสธ/ยกเลิก')], default='pending', max_length=20)),
                ('bank_name', models.CharField(choices=[('kbank', 'ธนาคารกสิกรไทย'), ('scb', 'ธนาคารไทยพาณิชย์'), ('bbl', 'ธนาคารกรุงเทพ'), ('ktb', 'ธนาคารกรุงไทย'), ('ttb', 'ธนาคารทหารไทยธนชาต (TTB)'), ('gsb', 'ธนาคารออมสิน'), ('bay', 'ธนาคารกรุงศรีอยุธยา'), ('promptpay', 'พร้อมเพย์'), ('other', 'อื่นๆ')], max_length=20)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('transfer_slip', models.ImageField(blank=True, null=True, upload_to='withdrawal_slips/')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller'], name='payments_wi_seller__a5ca6c_idx'), models.Index(fields=['status'], name='payments_wi_status_10ece7_idx'), models.Index(fields=['created_at'], name='payments_wi_created_db59ad_idx')],
            },
        ),
    ]
