# Generated by Django 5.0.6 on 2025-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
