# Generated by Django 5.0.6 on 2026-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_alter_livestream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.CharField(choices=[('preparing', 'กำลังเตรียม'), ('live', 'กำลังถ่ายทอด'), ('ended', 'จบแล้ว')], default='preparing', max_length=10),
        ),
    ]
