# Generated by Django 5.0.6 on 2026-01-13 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_shipped_at_order_shipping_carrier_and_more'),
        ('products', '0004_remove_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่รีวิว')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product', verbose_name='สินค้า')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รีวิว')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
            ],
            options={
                'verbose_name': 'รีวิว',
                'verbose_name_plural': 'รีวิว',
                'ordering': ['-created_at'],
            },
        ),
    ]
