# Generated by Django 5.0.6 on 2025-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='agora_channel_name',
            field=models.CharField(blank=True, help_text='Agora channel name for live streaming', max_length=255, null=True),
        ),
    ]
