# Generated by Django 5.0.6 on 2025-12-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_agora_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='agora_channel_name',
        ),
    ]
