# Generated by Django 5.0.6 on 2026-01-14 00:56

from django.db import migrations, models


def convert_scheduled_to_live(apps, schema_editor):
    """Convert any SCHEDULED auctions to LIVE"""
    Auction = apps.get_model('auctions', 'Auction')
    Auction.objects.filter(status='scheduled').update(status='live')


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_agora_channel_name'),
    ]

    operations = [
        # Data migration: convert scheduled to live
        migrations.RunPython(convert_scheduled_to_live, migrations.RunPython.noop),
        # Schema migration: update field choices and default
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='live', max_length=20),
        ),
    ]
