# Generated by Django 6.0.2 on 2026-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_scheduled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Auction duration in minutes, timer starts after admin approval'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
