# Generated by Django 5.0.6 on 2026-05-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_duration_minutes_alter_auction_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_at',
        ),
    ]
