# Generated by Django 5.0.6 on 2026-05-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Auction duration in minutes, timer starts after admin approval'),
        ),
        migrations.AddField(
            model_name='auction',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
