# Generated by Django 5.0.6 on 2026-05-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_duration_minutes_auction_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start_at',
        ),
    ]
