# Generated by Django 5.0.6 on 2026-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
