# Generated by Django 5.0.6 on 2025-12-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'รอการชำระเงิน'), ('waiting_soft_verify', 'รอตรวจสอบสลิป'), ('escrow_held', 'เงินอยู่ในระบบ'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ'), ('disputed', 'มีข้อพิพาท'), ('cancelled', 'ยกเลิกแล้ว')], default='pending_payment', max_length=20),
        ),
    ]
