# Generated by Django 5.0.6 on 2025-12-16 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('products', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_code',
            field=models.CharField(blank=True, help_text='รหัสอ้างอิงสำหรับใส่ในหมายเหตุการโอนเงิน', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference_code'], name='orders_orde_referen_1cc4b5_idx'),
        ),
    ]
