# Generated by Django 5.0.6 on 2025-12-24 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_reference_code_and_more'),
        ('products', '0004_remove_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_referen_1cc4b5_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_status',
            field=models.CharField(blank=True, help_text='Stripe payment status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'รอการชำระเงิน'), ('escrow_held', 'เงินอยู่ในระบบ'), ('shipped', 'จัดส่งแล้ว'), ('completed', 'สำเร็จ'), ('disputed', 'มีข้อพิพาท'), ('cancelled', 'ยกเลิกแล้ว')], default='pending_payment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stripe_payment_intent_id'], name='orders_orde_stripe__d5f9a9_idx'),
        ),
    ]
