# Generated by Django 5.0.6 on 2026-01-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipped_at_order_shipping_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_slug',
            field=models.CharField(blank=True, choices=[('thailand-post', 'ไปรษณีย์ไทย (Thailand Post)'), ('kerry-express-thailand', 'KEX Express'), ('flash-express', 'Flash Express'), ('ninjavan-thailand', 'Ninja Van'), ('dhl', 'DHL'), ('shopee-express-thailand', 'Shopee Express'), ('jtexpress-th', 'J&T Express'), ('best-express', 'Best Express'), ('other', 'อื่นๆ')], max_length=50, null=True, verbose_name='AfterShip Carrier Slug'),
        ),
    ]
