# Generated by Django 5.0.6 on 2026-02-04 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_carrier_slug'),
        ('products', '0006_product_is_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, verbose_name='เลขพัสดุ')),
                ('event_type', models.CharField(help_text='e.g., TRACKING_UPDATED, TRACKING_STOPPED', max_length=50, verbose_name='ประเภท event')),
                ('status_code', models.IntegerField(default=0, verbose_name='รหัสสถานะ')),
                ('substatus_code', models.IntegerField(default=0, verbose_name='รหัสสถานะย่อย')),
                ('status_tag', models.CharField(blank=True, help_text='e.g., InTransit, Delivered', max_length=50, verbose_name='สถานะ')),
                ('raw_data', models.JSONField(default=dict, verbose_name='ข้อมูลดิบจาก webhook')),
                ('dedupe_key', models.CharField(help_text='tracking_number|last_update_at|status|substatus', max_length=255, unique=True, verbose_name='Dedupe Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่จัดส่งถึง (จาก webhook)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier_slug',
            field=models.CharField(blank=True, choices=[('thailand-post', 'ไปรษณีย์ไทย (Thailand Post)'), ('kerry-express-thailand', 'KEX Express'), ('flash-express', 'Flash Express'), ('ninjavan-thailand', 'Ninja Van'), ('dhl', 'DHL'), ('shopee-express-thailand', 'Shopee Express'), ('jtexpress-th', 'J&T Express'), ('best-express', 'Best Express'), ('other', 'อื่นๆ')], max_length=50, null=True, verbose_name='Carrier Slug'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order this event belongs to (null if order not found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['tracking_number'], name='orders_trac_trackin_d45e56_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['order'], name='orders_trac_order_i_b07816_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['dedupe_key'], name='orders_trac_dedupe__494c86_idx'),
        ),
    ]
