# Generated by Django 5.0.6 on 2026-02-15 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('wrong_item', 'สินค้าไม่ตรงตามที่สั่ง'), ('damaged', 'สินค้าชำรุด/เสียหาย'), ('not_received', 'ไม่ได้รับสินค้า'), ('incomplete', 'สินค้าไม่ครบ'), ('other', 'อื่นๆ')], max_length=30, verbose_name='สาเหตุ')),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('evidence_1', models.ImageField(blank=True, null=True, upload_to='disputes/', verbose_name='หลักฐาน 1')),
                ('evidence_2', models.ImageField(blank=True, null=True, upload_to='disputes/', verbose_name='หลักฐาน 2')),
                ('evidence_3', models.ImageField(blank=True, null=True, upload_to='disputes/', verbose_name='หลักฐาน 3')),
                ('bank_name', models.CharField(choices=[('kbank', 'ธนาคารกสิกรไทย'), ('scb', 'ธนาคารไทยพาณิชย์'), ('bbl', 'ธนาคารกรุงเทพ'), ('ktb', 'ธนาคารกรุงไทย'), ('tmb', 'ธนาคารทหารไทยธนชาต (TTB)'), ('gsb', 'ธนาคารออมสิน'), ('bay', 'ธนาคารกรุงศรีอยุธยา'), ('promptpay', 'พร้อมเพย์'), ('other', 'อื่นๆ')], max_length=30, verbose_name='ธนาคาร')),
                ('bank_account_number', models.CharField(max_length=30, verbose_name='เลขบัญชี')),
                ('bank_account_name', models.CharField(max_length=100, verbose_name='ชื่อบัญชี')),
                ('status', models.CharField(choices=[('open', 'เปิดเคส'), ('under_review', 'กำลังตรวจสอบ'), ('resolved_refund', 'คืนเงินแล้ว'), ('resolved_partial', 'คืนเงินบางส่วน'), ('resolved_rejected', 'ปฏิเสธการคืนเงิน')], default='open', max_length=30, verbose_name='สถานะเคส')),
                ('admin_note', models.TextField(blank=True, verbose_name='หมายเหตุแอดมิน')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='จำนวนเงินคืน')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ตัดสิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตัดสิน')),
            ],
            options={
                'verbose_name': 'เคสข้อพิพาท',
                'verbose_name_plural': 'เคสข้อพิพาท',
                'ordering': ['-created_at'],
            },
        ),
    ]
