# Generated by Django 5.0.6 on 2026-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_disputecase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingEvent',
        ),
    ]
