# Generated by Django 5.0.6 on 2026-03-13 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_trackingevent'),
        ('products', '0006_product_is_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_wallet_credited',
            field=models.BooleanField(default=False, help_text='ระบุว่าออเดอร์นี้ถูกเครดิตเข้าวอลเล็ทผู้ขายแล้วหรือยัง'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller_wallet_credited'], name='orders_orde_seller__a22fba_idx'),
        ),
    ]
