# Generated by Django 5.0.6 on 2026-05-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_seller_wallet_credited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_delivered_at',
        ),
    ]
