# Generated by Django 5.0.6 on 2025-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'อิเล็กทรอนิกส์'), ('fashion', 'แฟชั่นและเครื่องแต่งกาย'), ('home', 'บ้านและสวน'), ('sports', 'กีฬาและกิจกรรมกลางแจ้ง'), ('books', 'หนังสือ'), ('toys', 'ของเล่นและงานอดิเรก'), ('beauty', 'ความงาม'), ('automotive', 'ยานยนต์'), ('pets', 'สัตว์เลี้ยง'), ('other', 'อื่นๆ')], default='other', max_length=80),
        ),
    ]
